package com.example.heroesapp.models

class HeroesDC(val id: Int, val name: String, val image: String, val description: String) {
    companion object {
        val heroesDC = mutableListOf<HeroesDC>(
            HeroesDC(1, "Batman", "https://hips.hearstapps.com/hmg-prod/images/batman-1646054773.jpeg?crop=0.5625xw:1xh;center,top&resize=640:*", "Batman es el alter ego de Bruce Wayne, un multimillonario empresario que, tras presenciar el asesinato de sus padres cuando era niño, decide combatir el crimen en Gotham City. Utilizando su intelecto, habilidades detectivescas, y tecnología avanzada, Batman no posee superpoderes pero es uno de los mayores tácticos y combatientes cuerpo a cuerpo del mundo DC. Es conocido por su enfoque en la justicia y su voluntad de usar el miedo contra los criminales."),
            HeroesDC(2, "Superman", "https://ew.com/thmb/IWTSy6GrKCmZBSIcZwC84oHmNdw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/mos-10175c_2-2000-116d947875b84ddcabb01baa1fa1b389.jpg", "Superman es el último hijo de Krypton, enviado a la Tierra desde su planeta natal justo antes de su destrucción. Criado como Clark Kent en Kansas, descubre que posee habilidades sobrehumanas, incluyendo vuelo, fuerza inmensurable, y resistencia. Como Superman, se convierte en el defensor de la Tierra y un símbolo de esperanza para la humanidad, siempre luchando por la verdad y la justicia."),
            HeroesDC(3, "Wonder", "https://static.wikia.nocookie.net/dccu/images/6/6f/JL_Wonder_Woman.jpg/revision/latest?cb=20160914003449", "Wonder Woman es la princesa Diana de las Amazonas, entrenada para ser una guerrera invencible en la isla oculta de Themyscira. Al descubrir el mundo exterior, se convierte en Wonder Woman, una embajadora de la paz dotada con superpoderes otorgados por los dioses, incluyendo fuerza sobrehumana y agilidad, además de armas mágicas como el Lazo de la Verdad. Es uno de los miembros fundadores de la Liga de la Justicia."),
            HeroesDC(4, "Flash", "https://i.blogs.es/d60e27/the-flash/840_560.jpeg", "Flash es el alias de Barry Allen, un científico forense que gana la habilidad de moverse a velocidades sobrehumanas después de ser alcanzado por un rayo y bañado en productos químicos. Como el hombre más rápido vivo, utiliza sus poderes para combatir el crimen a través del tiempo y el espacio multidimensional. Flash es bien conocido por su capacidad de alterar la realidad temporal, haciendo de él uno de los héroes más poderosos y versátiles de DC."),
            HeroesDC(5, "Green Lantern", "https://static.wikia.nocookie.net/marvel_dc/images/8/83/Hal_Jordan_and_the_Green_Lantern_Corps_Vol_1_45_Textless_Variant.jpg/revision/latest?cb=20180523193425", "Green Lantern es el nombre de Hal Jordan después de ser seleccionado por el anillo de poder de la linterna verde, que le otorga la habilidad de crear manifestaciones físicas de su voluntad a través del poder de la imaginación. Como miembro de los Green Lantern Corps, una fuerza policial interestelar, Hal protege el universo de amenazas cósmicas, utilizando su anillo para volar y generar construcciones de energía con cualquier forma o tamaño que desee."),
        )
    }
}